//https://sandbox.viafirma.com/documents/api/v3/

GET https://sandbox.viafirma.com/documents/api/v3/system/alive
Authorization: "Basic UHJvY3JlZGl0bzpvbGtzck1WTXU="

{

}



###Login Api

GET http://localhost:8000/procredito/loginapi

{
	
}


###Lista plantilla

GET https://sandbox.viafirma.com/documents/api/v3/system/alive
Authorization: "Basic UHJvY3JlZGl0bzpvbGtzck1WTXU="

{
	
}

###Lista plantilla

GET https://services.viafirma.com/documents/api/v3/template/list/andreinamejiaparedes@gmail.com
content-type: application/x-www-form-urlencoded
authorization: Basic cHJvY3JlZGl0b19kb21pbmljYW5hOk1ENDNTQQ==

{
	
}



###Login Api

POST https://itmsrdbackend.herokuapp.com/procredito/submitForm
content-type: application/json

{
 "tipoenvio":"1",
  "emailDestino": "soriano.marvin@gmail.com",
  "infoCliente": {
    "nombre": "Dionys",
    "cedula": "002-0153781-8",
    "direccion": "fjhddfg",
    "celular": "+18096579005",
    "ciudad": "sdfg",
    "celular2": "",
    "dia": "",
    "mes": "",
    "ano": ""
  }
}


###Login Api

POST https://itmsrdbackend.herokuapp.com/procredito/submitForm
content-type: application/json

{ 
"tipoenvio":"1",
"emailDestino":"",
"infoCliente": {
      "nombre":"",
      "cedula":"",
      "direccion":"",
      "celular":"+18096579005",
      "ciudad":"",
      "celular2":"",
      "dia":"2",
      "mes":"3",
      "ano":"2022"
      } 
}


#{
#  "tipoenvio":"1",
#  "emailDestino": "ing.dionisc@gmail.com",
#  "infoCliente": {
#    "nombre": "Dionys",
#    "cedula": "002-0153781-8",
#    "direccion": "fjhddfg",
#    "celular": "+18096579005",
#    "ciudad": "sdfg",
#    "celular2": "",
#    "dia": "",
#    "mes": "",
#    "ano": ""
#  }
#}

###
GET http://localhost:8000/procredito/bcedula/002-0129406-3
content-type: application/json

{ 

}


###
GET http://localhost:8000/procredito/loaddata
content-type: application/json

{ 

}