###
GET http://localhost:8000/itmsshipping/apptoken/OPENSEASSHIPPING 

{

}


###- Get Config
GET http://localhost:8000/itmsshipping/userlist 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbnRlcklkIjoiT1BFTlNFQVNTSElQUElORyIsImlhdCI6MTY0OTE4MTIyNCwiZXhwIjoxNjQ5MjAyODI0fQ.0tphiruFQcfNF-ETf1Me_CaowWxnH21dpVLRqf4FpsA

{

}


###- Get User
GET http://localhost:8000/itmsshipping/config/OPENSEASSHIPPING 

{

}


###- Find Form
GET  http://localhost:8000/itmsshipping/findForm/000000013/1 
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbnRlcklkIjoiT1BFTlNFQVNTSElQUElORyIsImlhdCI6MTY0OTE4MTIyNCwiZXhwIjoxNjQ5MjAyODI0fQ.0tphiruFQcfNF-ETf1Me_CaowWxnH21dpVLRqf4FpsA

{

}



###- Find Form
GET  http://localhost:8000/itmsshipping/createForm 
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbnRlcklkIjoiT1BFTlNFQVNTSElQUElORyIsImlhdCI6MTY0OTE4MTIyNCwiZXhwIjoxNjQ5MjAyODI0fQ.0tphiruFQcfNF-ETf1Me_CaowWxnH21dpVLRqf4FpsA

{

}