###
GET http://192.168.10.235:8000/itmsshipping/apptoken/OPENSEASSHIPPING 

{

}


###- Get Config
GET http://192.168.10.235:8000/itmsshipping/userlist 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbnRlcklkIjoiT1BFTlNFQVNTSElQUElORyIsImlhdCI6MTY0OTY4ODk1MSwiZXhwIjoxNjQ5NzEwNTUxfQ.Xfx4r38wFLFsaQG3ys7uorTHAV_O1RdFQyjnjc7BDLI
{

}


###- Get User
GET http://192.168.10.235:8000/itmsshipping/config/OPENSEASSHIPPING 

{

}


###- Find Form
GET  http://192.168.10.235:8000/itmsshipping/findForm/000000013/1 
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbnRlcklkIjoiT1BFTlNFQVNTSElQUElORyIsImlhdCI6MTY0OTY4ODk1MSwiZXhwIjoxNjQ5NzEwNTUxfQ.Xfx4r38wFLFsaQG3ys7uorTHAV_O1RdFQyjnjc7BDLI
{

}

###- Save Form
post  http://192.168.10.235:8000/itmsshipping/saveForm
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbnRlcklkIjoiT1BFTlNFQVNTSElQUElORyIsImlhdCI6MTY0OTY4ODk1MSwiZXhwIjoxNjQ5NzEwNTUxfQ.Xfx4r38wFLFsaQG3ys7uorTHAV_O1RdFQyjnjc7BDLI
{
 "FormID": "91AB8A05-C867-4E64-AB98-AD2C8D3EA517", 
 "UserID": "0003" ,
 "SignName": "JUAN ARELIS RODRIGUEZ", 
 "SignUrl": "https://res.cloudinary.com/dfbwtygxk/image/upload/v1648179601/itms/shipping/firmas/hfjq6zzkwta8ot2mxdsz.png"
 }


###- create Form
get  http://192.168.10.235:8000/itmsshipping/createForm
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbnRlcklkIjoiT1BFTlNFQVNTSElQUElORyIsImlhdCI6MTY0OTY4ODk1MSwiZXhwIjoxNjQ5NzEwNTUxfQ.Xfx4r38wFLFsaQG3ys7uorTHAV_O1RdFQyjnjc7BDLI
{

}

###- create Form
POST   http://192.168.10.235:8000/itmsshipping/saveNewForm
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbnRlcklkIjoiT1BFTlNFQVNTSElQUElORyIsImlhdCI6MTY0OTY4ODk1MSwiZXhwIjoxNjQ5NzEwNTUxfQ.Xfx4r38wFLFsaQG3ys7uorTHAV_O1RdFQyjnjc7BDLI

{
"RowUsr":"dfsdfsdfsdfs",
"formbody":{
  "shippingform-01-01": "hkjhk",
  "shippingform-01-02": "yiytuityuit",
  "shippingform-01-03": "iityuity",
  "shippingform-01-04": "8967896789",
  "shippingform-01-05": "ID OR PASSPORT",
  "shippingform-01-06": "yuityui",
  "shippingform-01-07": "yuityi",
  "shippingform-02-01": "tityuity",
  "shippingform-02-02": "uitiut",
  "shippingform-02-03": "uitiu",
  "shippingform-02-04": "987976896",
  "shippingform-02-05": "SDQ - REP.DOM",
  "shippingform-02-06": "uioyuioyuoyuio",
  "shippingform-03-01": "COOKWAVRE",
  "shippingform-03-02": "jhkghkgjhk89",
  "shippingform-03-03": "8989",
  "shippingform-03-04": "DOOR TO DOOR DELIVERY REQUIRED",
  "shippingform-04-01": "10",
  "shippingform-04-02": "gjhkgk",
  "shippingform-04-03": "789",
  "shippingform-04-04": "8",
  "shippingform-04-05": "8",
  "shippingform-04-06": "678",
  "shippingform-04-07": "hjkjhgkghjk hjk",
  "shippingform-04-08": "5"
}

}