###
GET http://192.168.0.3:8000/itmsshipping/apptoken/OPENSEASSHIPPING 

{

}


###- Get Config
GET http://192.168.0.3:8000/itmsshipping/userlist 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbnRlcklkIjoiT1BFTlNFQVNTSElQUElORyIsImlhdCI6MTY0OTIyMjY1NywiZXhwIjoxNjQ5MjQ0MjU3fQ.TFb5-OuU9WwVVu5YLkWoplzBJe80OQJk1hZVIxnUf5o

{

}


###- Get User
GET http://192.168.0.3:8000/itmsshipping/config/OPENSEASSHIPPING 

{

}


###- Find Form
GET  http://192.168.0.3:8000/itmsshipping/findForm/000000013/1 
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbnRlcklkIjoiT1BFTlNFQVNTSElQUElORyIsImlhdCI6MTY0OTIyMjY1NywiZXhwIjoxNjQ5MjQ0MjU3fQ.TFb5-OuU9WwVVu5YLkWoplzBJe80OQJk1hZVIxnUf5o

{

}

###- Save Form
post  http://192.168.0.3:8000/itmsshipping/saveForm
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbnRlcklkIjoiT1BFTlNFQVNTSElQUElORyIsImlhdCI6MTY0OTIyMjY1NywiZXhwIjoxNjQ5MjQ0MjU3fQ.TFb5-OuU9WwVVu5YLkWoplzBJe80OQJk1hZVIxnUf5o

{
 "FormID": "91AB8A05-C867-4E64-AB98-AD2C8D3EA517", 
 "UserID": "0003" ,
 "SignName": "JUAN ARELIS RODRIGUEZ", 
 "SignUrl": "https://res.cloudinary.com/dfbwtygxk/image/upload/v1648179601/itms/shipping/firmas/hfjq6zzkwta8ot2mxdsz.png"
 }


###- create Form
get  http://192.168.0.3:8000/itmsshipping/createForm
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbnRlcklkIjoiT1BFTlNFQVNTSElQUElORyIsImlhdCI6MTY0OTIyMjY1NywiZXhwIjoxNjQ5MjQ0MjU3fQ.TFb5-OuU9WwVVu5YLkWoplzBJe80OQJk1hZVIxnUf5o

{

}
